version: "3.5"

services:
    python:
        build: .
        container_name: python
        hostname: python
        expose:
            - 5000
        volumes:
            - .:/app:ro
        command: /usr/local/bin/gunicorn -k gevent --reload --workers 10 --worker-connections 10 --access-logfile=- --pythonpath /app -b :5000 app:app

    nginx_flask:
        restart: always
        image: nginx:latest
        hostname: nginx_flask
        container_name: nginx_flask
        ports:
            - "8080:8080"
        volumes:
            - ./static:/www/static:ro
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf


