version: "3.5"

services:
  python:
    build: .
    container_name: python
    hostname: python
    expose:
      - 5000
    volumes:
      - .:/app:ro
    command: /usr/local/bin/gunicorn -k gevent --reload --workers 10 --worker-connections 10 --access-logfile=- --pythonpath /app -b :5000 app:app

  nginx_flask:
    restart: always
    image: nginx:latest
    hostname: nginx_flask
    container_name: nginx_flask
    ports:
      - "8080:8080"
    volumes:
      - ./static:/www/static:ro
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql_flask:
    image: mariadb:10.2
    container_name: mysql_flask
    restart: unless-stopped
    tty: true
    ports:
      - "12306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    read_only: false
